### ISSUE TITLE
Get tag Identifier method

### ISSUE THREAD

**Issue by UnexpectedLobster** [RoopeHakulinen/cordova-plugin-mifare-ultralight#1]
It would be useful to get the tag GUID on the mifare.connect() callback.
Found that getId() could be used on the discovered the java Tag object. (see https://developer.android.com/reference/android/nfc/Tag.html)

**Comment by RoopeHakulinen** [comment]
Thank you for your feedback. 

I had a look at it and was wondering whether it should actually be sent when tag is discovered (that is when _mifareTagDiscovered_ event is sent) instead of after tag has been connected. Do you agree that would be more logical? It could also be sent by both, on tag found event and after connected?

Anyways, it can definitely be added as soon as the above is resolved.

**Comment by RoopeHakulinen** [comment]
I just released version 1.0.1 with fix for the _mifareTagDiscovered_ event not containing the tag id. This was the behavior intended but was forgotten to be added at the time of releasing the 1.0.0. 

Please let me know if there is a use case for the id to be returned as the connect method result.

**Comment by RoopeHakulinen** [comment]
Ping @PymZoR

**Comment by UnexpectedLobster** [comment]
@RoopeHakulinen Really sorry for disappearing like this.

Getting the guid on discover seems more logical as it can be used as a filter before connecting to a tag, and (correct me if i'm wrong) a tag must be discovered before any connection. It's therefore seems to me perfectly fine the way you handled it. Thanks :+1:
